function g(a){return function(){return this[a]}}var l,o=this;function aa(){}
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a){return ba(a)=="array"}function da(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"}function p(a){return typeof a=="string"}function q(a){return typeof a=="number"}function ea(a){return ba(a)=="function"}function fa(a){a=ba(a);return a=="object"||a=="array"||a=="function"}function ga(a){if(a.hasOwnProperty&&a.hasOwnProperty(ha))return a[ha];a[ha]||(a[ha]=++ia);return a[ha]}
var ha="closure_hashCode_"+Math.floor(Math.random()*2147483648).toString(36),ia=0;function ja(a){var b=ba(a);if(b=="object"||b=="array"){if(a.K)return a.K.call(a);b=b=="array"?[]:{};for(var c in a)b[c]=ja(a[c]);return b}return a}function ka(a,b){var c=b||o;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}}
var la=Date.now||function(){return+new Date};function s(a,b){function c(){}c.prototype=b.prototype;a.f=b.prototype;a.prototype=new c;a.prototype.constructor=a};var t=Array.prototype,ma=t.indexOf?function(a,b,c){return t.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(p(a)){if(!p(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=t.forEach?function(a,b,c){t.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},oa=t.map?function(a,b,c){return t.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=new Array(d),
f=p(a)?a.split(""):a,h=0;h<d;h++)if(h in f)e[h]=b.call(c,f[h],h,a);return e};function pa(a,b){var c=ma(a,b),d;if(d=c>=0)t.splice.call(a,c,1);return d}function qa(){return t.concat.apply(t,arguments)}function ra(a){if(ca(a))return qa(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function sa(a,b,c){return arguments.length<=2?t.slice.call(a,b):t.slice.call(a,b,c)};var ta;function ua(a){var b;b=(b=a.className)&&typeof b.split=="function"?b.split(/\s+/):[];var c;c=sa(arguments,1);for(var d=0,e=0;e<c.length;e++)if(!(ma(b,c[e])>=0)){b.push(c[e]);d++}c=d==c.length;a.className=b.join(" ");return c};function va(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}va.prototype.K=function(){return new va(this.x,this.y)};va.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function u(a,b){this.width=a;this.height=b}l=u.prototype;l.K=function(){return new u(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
l.scale=function(a){this.width*=a;this.height*=a;return this};function wa(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function xa(a,b){var c;if(c=b in a)delete a[b];return c}var ya=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];function za(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<ya.length;e++){b=ya[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};function Aa(a,b){if(b)return a.replace(Ba,"&amp;").replace(Ca,"&lt;").replace(Da,"&gt;").replace(Ea,"&quot;");else{if(!Fa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ba,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ca,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Da,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ea,"&quot;");return a}}var Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/\"/g,Fa=/[&<>\"]/;
function Ga(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;c==0&&h<f;h++){var j=d[h]||"",i=e[h]||"",k=new RegExp("(\\d*)(\\D*)","g"),r=new RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(j)||["","",""],m=r.exec(i)||["","",""];if(n[0].length==0&&m[0].length==0)break;c=Ha(n[1].length==0?0:parseInt(n[1],10),m[1].length==0?0:parseInt(m[1],10))||Ha(n[2].length==0,m[2].length==0)||Ha(n[2],
m[2])}while(c==0)}return c}function Ha(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}var Ia=la();var v,Ja,Ka,La,Ma;function Na(){return o.navigator?o.navigator.userAgent:null}Ma=La=Ka=Ja=v=false;var Oa;if(Oa=Na()){var Pa=o.navigator;v=Oa.indexOf("Opera")==0;Ja=!v&&Oa.indexOf("MSIE")!=-1;La=(Ka=!v&&Oa.indexOf("WebKit")!=-1)&&Oa.indexOf("Mobile")!=-1;Ma=!v&&!Ka&&Pa.product=="Gecko"}var Qa=v,Ra=Ja,Sa=Ma,w=Ka,Ta=La,Ua=o.navigator,Va=(Ua&&Ua.platform||"").indexOf("Mac")!=-1,Wa,Xa="",Ya;
if(Qa&&o.opera){var Za=o.opera.version;Xa=typeof Za=="function"?Za():Za}else{if(Sa)Ya=/rv\:([^\);]+)(\)|;)/;else if(Ra)Ya=/MSIE\s+([^\);]+)(\)|;)/;else if(w)Ya=/WebKit\/(\S+)/;if(Ya){var $a=Ya.exec(Na());Xa=$a?$a[1]:""}}Wa=Xa;var ab={};function x(a){return ab[a]||(ab[a]=Ga(Wa,a)>=0)};function bb(a){return a?new cb(db(a)):ta||(ta=new cb)}
function eb(a,b,c,d){d=d||a;b=b&&b!="*"?b.toUpperCase():"";if(d.querySelectorAll&&(b||c)&&(!w||a.compatMode=="CSS1Compat"||x("528")))return d.querySelectorAll(b+(c?"."+c:""));if(c&&d.getElementsByClassName){a=d.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)if(b==h.nodeName)d[e++]=h;d.length=e;return d}else return a}a=d.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++){b=h.className;if(typeof b.split=="function"&&ma(b.split(/\s+/),c)>=0)d[e++]=h}d.length=e;return d}else return a}
function fb(a,b){wa(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in gb)a.setAttribute(gb[d],c);else a[d]=c})}var gb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function hb(a,b){var c=b[0],d=b[1];if(Ra&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',Aa(d.name),'"');if(d.type){c.push(' type="',Aa(d.type),'"');d=ja(d);delete d.type}c.push(">");c=c.join("")}var e=a.createElement(c);if(d)if(p(d))e.className=d;else fb(e,d);if(b.length>2){d=function(h){if(h)e.appendChild(p(h)?a.createTextNode(h):h)};for(c=2;c<b.length;c++){var f=b[c];da(f)&&!(fa(f)&&f.nodeType>0)?na(ib(f)?ra(f):f,d):d(f)}}return e}
function jb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function db(a){return a.nodeType==9?a:a.ownerDocument||a.document}function ib(a){if(a&&typeof a.length=="number")if(fa(a))return typeof a.item=="function"||typeof a.item=="string";else if(ea(a))return typeof a.item=="function";return false}function cb(a){this.w=a||o.document||document}l=cb.prototype;l.fa=bb;l.a=function(a){return p(a)?this.w.getElementById(a):a};l.fb=function(a,b,c){return eb(this.w,a,b,c)};l.cb=cb.prototype.fb;
l.sb=fb;l.p=function(){return hb(this.w,arguments)};l.createElement=function(a){return this.w.createElement(a)};l.createTextNode=function(a){return this.w.createTextNode(a)};l.appendChild=function(a,b){a.appendChild(b)};l.removeNode=jb;function y(a){return a*Math.PI/180};function A(){this.g=[];this.c=[];this.F=[]}A.prototype.ca=null;A.prototype.h=null;A.prototype.ia=true;var B=[];B[0]=2;B[1]=2;B[2]=6;B[3]=6;B[4]=0;l=A.prototype;l.moveTo=function(a,b){if(this.g[this.g.length-1]==0)this.F.length-=2;else{this.g.push(0);this.c.push(1)}this.F.push(a,b);this.h=this.ca=[a,b];return this};
l.lineTo=function(){var a=this.g[this.g.length-1];if(a==null)throw Error("Path cannot start with lineTo");if(a!=1){this.g.push(1);this.c.push(0)}for(a=0;a<arguments.length;a+=2){var b=arguments[a],c=arguments[a+1];this.F.push(b,c)}this.c[this.c.length-1]+=a/2;this.h=[b,c];return this};
l.Oa=function(){var a=this.g[this.g.length-1];if(a==null)throw Error("Path cannot start with curve");if(a!=2){this.g.push(2);this.c.push(0)}for(a=0;a<arguments.length;a+=6){var b=arguments[a+4],c=arguments[a+5];this.F.push(arguments[a],arguments[a+1],arguments[a+2],arguments[a+3],b,c)}this.c[this.c.length-1]+=a/6;this.h=[b,c];return this};l.close=function(){var a=this.g[this.g.length-1];if(a==null)throw Error("Path cannot start with close");if(a!=4){this.g.push(4);this.c.push(1);this.h=this.ca}return this};
l.arc=function(a,b,c,d,e,f,h){a=a+c*Math.cos(y(e));b=b+d*Math.sin(y(e));if(h){if(!this.h||a!=this.h[0]||b!=this.h[1])this.lineTo(a,b)}else this.moveTo(a,b);return this.arcTo(c,d,e,f)};l.arcTo=function(a,b,c,d){var e=this.h[0]-a*Math.cos(y(c)),f=this.h[1]-b*Math.sin(y(c));e=e+a*Math.cos(y(c+d));f=f+b*Math.sin(y(c+d));this.g.push(3);this.c.push(1);this.F.push(a,b,c,d,e,f);this.ia=false;this.h=[e,f];return this};
l.db=function(a,b,c,d){var e=this.h[0]-a*Math.cos(y(c)),f=this.h[1]-b*Math.sin(y(c)),h=y(d);d=Math.ceil(Math.abs(h)/Math.PI*2);h=h/d;c=y(c);for(var j=0;j<d;j++){var i=Math.cos(c),k=Math.sin(c),r=4/3*Math.sin(h/2)/(1+Math.cos(h/2)),n=e+(i-r*k)*a,m=f+(k+r*i)*b;c+=h;i=Math.cos(c);k=Math.sin(c);this.Oa(n,m,e+(i+r*k)*a,f+(k-r*i)*b,e+i*a,f+k*b)}return this};function kb(a,b){for(var c=a.F,d=0,e=0,f=a.g.length;e<f;e++){var h=a.g[e],j=B[h]*a.c[e];b(h,c.slice(d,d+j));d+=j}}
A.prototype.K=function(){var a=new this.constructor;a.g=this.g.concat();a.c=this.c.concat();a.F=this.F.concat();a.ca=this.ca&&this.ca.concat();a.h=this.h&&this.h.concat();a.ia=this.ia;return a};var C={};C[0]=A.prototype.moveTo;C[1]=A.prototype.lineTo;C[4]=A.prototype.close;C[2]=A.prototype.Oa;C[3]=A.prototype.db;function lb(a){if(a.ia)return a.K();var b=new A;kb(a,function(c,d){C[c].apply(b,d)});return b};function mb(a,b,c){if(b instanceof u){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}a.style.width=typeof b=="number"?Math.round(b)+"px":b;a.style.height=typeof c=="number"?Math.round(c)+"px":c}
function D(a){var b=Qa&&!x("10"),c;a:{c=db(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,"")){c=c.display;break a}c=null}if((c||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!="none")return b?new u(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new u(a.offsetWidth,a.offsetHeight);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;
a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=f;c.visibility=e;return new u(b,a)};function E(){}E.prototype.Ra=false;E.prototype.N=function(){if(!this.Ra){this.Ra=true;this.b()}};E.prototype.b=function(){};function F(a,b){this.type=a;this.currentTarget=this.target=b}s(F,E);F.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};F.prototype.Z=false;F.prototype.va=true;function G(a,b){a&&this.ra(a,b)}s(G,F);l=G.prototype;l.target=null;l.relatedTarget=null;l.offsetX=0;l.offsetY=0;l.clientX=0;l.clientY=0;l.screenX=0;l.screenY=0;l.button=0;l.keyCode=0;l.charCode=0;l.ctrlKey=false;l.altKey=false;l.shiftKey=false;l.metaKey=false;l.pb=false;l.Sa=null;
l.ra=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(Sa)try{d=d.nodeName&&d}catch(e){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pb=Va?a.metaKey:a.ctrlKey;this.Sa=a;delete this.va;delete this.Z};Ra&&x("8");G.prototype.b=function(){G.f.b.call(this);this.relatedTarget=this.currentTarget=this.target=this.Sa=null};function nb(){}var ob=0;l=nb.prototype;l.key=0;l.aa=false;l.Na=false;l.ra=function(a,b,c,d,e,f){if(ea(a))this.Wa=true;else if(a&&a.handleEvent&&ea(a.handleEvent))this.Wa=false;else throw Error("Invalid listener argument");this.X=a;this.Za=b;this.src=c;this.type=d;this.capture=!!e;this.qa=f;this.Na=false;this.key=++ob;this.aa=false};l.handleEvent=function(a){if(this.Wa)return this.X.call(this.qa||this.src,a);return this.X.handleEvent.call(this.X,a)};function H(a,b){this.Xa=b;this.P=[];if(a>this.Xa)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.P.push(this.v?this.v():{})}s(H,E);H.prototype.v=null;H.prototype.Qa=null;function I(a){if(a.P.length)return a.P.pop();return a.v?a.v():{}}function J(a,b){a.P.length<a.Xa?a.P.push(b):pb(a,b)}function pb(a,b){if(a.Qa)a.Qa(b);else if(ea(b.N))b.N();else for(var c in b)delete b[c]}
H.prototype.b=function(){H.f.b.call(this);for(var a=this.P;a.length;)pb(this,a.pop());delete this.P};var qb;var rb=(qb="ScriptEngine"in o&&o.ScriptEngine()=="JScript")?o.ScriptEngineMajorVersion()+"."+o.ScriptEngineMinorVersion()+"."+o.ScriptEngineBuildVersion():"0";var sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb;
(function(){function a(){return{c:0,s:0}}function b(){return[]}function c(){function m(z){return h.call(m.src,m.key,z)}return m}function d(){return new nb}function e(){return new G}var f=qb&&!(Ga(rb,"5.7")>=0),h;xb=function(m){h=m};if(f){sb=function(){return I(j)};tb=function(m){J(j,m)};ub=function(){return I(i)};vb=function(m){J(i,m)};wb=function(){return I(k)};yb=function(){J(k,c())};zb=function(){return I(r)};Ab=function(m){J(r,m)};Bb=function(){return I(n)};Cb=function(m){J(n,m)};var j=new H(0,
600);j.v=a;var i=new H(0,600);i.v=b;var k=new H(0,600);k.v=c;var r=new H(0,600);r.v=d;var n=new H(0,600);n.v=e}else{sb=a;tb=aa;ub=b;vb=aa;wb=c;yb=aa;zb=d;Ab=aa;Bb=e;Cb=aa}})();var K={},L={},M={},Db={};
function Eb(a,b,c,d,e){if(b)if(ca(b)){for(var f=0;f<b.length;f++)Eb(a,b[f],c,d,e);return null}else{d=!!d;var h=L;b in h||(h[b]=sb());h=h[b];if(!(d in h)){h[d]=sb();h.c++}h=h[d];var j=ga(a),i;h.s++;if(h[j]){i=h[j];for(f=0;f<i.length;f++){h=i[f];if(h.X==c&&h.qa==e){if(h.aa)break;return i[f].key}}}else{i=h[j]=ub();h.c++}f=wb();f.src=a;h=zb();h.ra(c,f,a,b,d,e);c=h.key;f.key=c;i.push(h);K[c]=h;M[j]||(M[j]=ub());M[j].push(h);if(a.addEventListener){if(a==o||!a.za)a.addEventListener(b,f,d)}else a.attachEvent(Fb(b),
f);return c}else throw Error("Invalid event type");}function Gb(a,b,c,d,e){if(ca(b)){for(var f=0;f<b.length;f++)Gb(a,b[f],c,d,e);return null}d=!!d;a=Hb(a,b,d);if(!a)return false;for(f=0;f<a.length;f++)if(a[f].X==c&&a[f].capture==d&&a[f].qa==e)return N(a[f].key);return false}
function N(a){if(!K[a])return false;var b=K[a];if(b.aa)return false;var c=b.src,d=b.type,e=b.Za,f=b.capture;if(c.removeEventListener){if(c==o||!c.za)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(Fb(d),e);c=ga(c);e=L[d][f][c];if(M[c]){var h=M[c];pa(h,b);h.length==0&&delete M[c]}b.aa=true;e.Ya=true;Ib(d,f,c,e);delete K[a];return true}
function Ib(a,b,c,d){if(!d.ta)if(d.Ya){for(var e=0,f=0;e<d.length;e++)if(d[e].aa){var h=d[e].Za;h.src=null;yb(h);Ab(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Ya=false;if(f==0){vb(d);delete L[a][b][c];L[a][b].c--;if(L[a][b].c==0){tb(L[a][b]);delete L[a][b];L[a].c--}if(L[a].c==0){tb(L[a]);delete L[a]}}}}
function Jb(a,b,c){var d=0,e=b==null,f=c==null;c=!!c;if(a==null)wa(M,function(i){for(var k=i.length-1;k>=0;k--){var r=i[k];if((e||b==r.type)&&(f||c==r.capture)){N(r.key);d++}}});else{a=ga(a);if(M[a]){a=M[a];for(var h=a.length-1;h>=0;h--){var j=a[h];if((e||b==j.type)&&(f||c==j.capture)){N(j.key);d++}}}}return d}function Hb(a,b,c){var d=L;if(b in d){d=d[b];if(c in d){d=d[c];a=ga(a);if(d[a])return d[a]}}return null}function Fb(a){if(a in Db)return Db[a];return Db[a]="on"+a}
function Kb(a,b,c,d,e){var f=1;b=ga(b);if(a[b]){a.s--;a=a[b];if(a.ta)a.ta++;else a.ta=1;try{for(var h=a.length,j=0;j<h;j++){var i=a[j];if(i&&!i.aa)f&=Lb(i,e)!==false}}finally{a.ta--;Ib(c,d,b,a)}}return Boolean(f)}function Lb(a,b){var c=a.handleEvent(b);a.Na&&N(a.key);return c}
xb(function(a,b){if(!K[a])return true;var c=K[a],d=c.type,e=L;if(!(d in e))return true;e=e[d];var f,h;if(Ra){var j;if(!(j=b))a:{j="window.event".split(".");for(var i=o;f=j.shift();)if(i[f])i=i[f];else{j=null;break a}j=i}f=j;j=true in e;i=false in e;if(j){if(f.keyCode<0||f.returnValue!=undefined)return true;a:{var k=false;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(r){k=true}if(k||f.returnValue==undefined)f.returnValue=true}}k=Bb();k.ra(f,this);f=true;try{if(j){for(var n=ub(),m=k.currentTarget;m;m=
m.parentNode)n.push(m);h=e[true];h.s=h.c;for(var z=n.length-1;!k.Z&&z>=0&&h.s;z--){k.currentTarget=n[z];f&=Kb(h,n[z],d,true,k)}if(i){h=e[false];h.s=h.c;for(z=0;!k.Z&&z<n.length&&h.s;z++){k.currentTarget=n[z];f&=Kb(h,n[z],d,false,k)}}}else f=Lb(c,k)}finally{if(n){n.length=0;vb(n)}k.N();Cb(k)}return f}d=new G(b,this);try{f=Lb(c,d)}finally{d.N()}return f});function O(a){this.Q=a}s(O,E);var Mb=new H(0,100);function Nb(a,b,c,d,e,f){if(ca(c))for(var h=0;h<c.length;h++)Nb(a,b,c[h],d,e,f);else{b=Eb(b,c,d||a,e||false,f||a.Q||a);if(a.r)a.r[b]=true;else if(a.H){a.r=I(Mb);a.r[a.H]=true;a.H=null;a.r[b]=true}else a.H=b}return a}
function Ob(a,b,c,d,e,f){if(a.H||a.r)if(ca(c))for(var h=0;h<c.length;h++)Ob(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.Q||a;e=!!(e||false);if(b=Hb(b,c,e))for(c=0;c<b.length;c++)if(b[c].X==d&&b[c].capture==e&&b[c].qa==f){b=b[c];break a}b=null}if(b){b=b.key;N(b);if(a.r)xa(a.r,b);else if(a.H==b)a.H=null}}return a}function Pb(a){if(a.r){for(var b in a.r){N(b);delete a.r[b]}J(Mb,a.r);a.r=null}else a.H&&N(a.H)}O.prototype.b=function(){O.f.b.call(this);Pb(this)};
O.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function P(){}s(P,E);l=P.prototype;l.za=true;l.ua=null;l.Ha=function(a){this.ua=a};l.addEventListener=function(a,b,c,d){Eb(this,a,b,c,d)};l.removeEventListener=function(a,b,c,d){Gb(this,a,b,c,d)};
l.dispatchEvent=function(a){a=a;if(p(a))a=new F(a,this);else if(a instanceof F)a.target=a.target||this;else{var b=a;a=new F(a.type,this);za(a,b)}b=1;var c,d=a.type,e=L;if(d in e){e=e[d];d=true in e;var f;if(d){c=[];for(f=this;f;f=f.ua)c.push(f);f=e[true];f.s=f.c;for(var h=c.length-1;!a.Z&&h>=0&&f.s;h--){a.currentTarget=c[h];b&=Kb(f,c[h],a.type,true,a)&&a.va!=false}}if(false in e){f=e[false];f.s=f.c;if(d)for(h=0;!a.Z&&h<c.length&&f.s;h++){a.currentTarget=c[h];b&=Kb(f,c[h],a.type,false,a)&&a.va!=false}else for(c=
this;!a.Z&&c&&f.s;c=c.ua){a.currentTarget=c;b&=Kb(f,c,a.type,false,a)&&a.va!=false}}a=Boolean(b)}else a=true;return a};l.b=function(){P.f.b.call(this);Jb(this);this.ua=null};function Qb(){}(function(a){a.Ta=function(){return a.kb||(a.kb=new a)}})(Qb);Qb.prototype.nb=0;Qb.Ta();function Q(a){this.k=a||bb();this.rb=Rb}s(Q,P);Q.prototype.jb=Qb.Ta();var Rb=null;l=Q.prototype;l.W=null;l.k=null;l.i=false;l.e=null;l.rb=null;l.mb=null;l.Y=null;l.o=null;l.na=null;l.bb=false;l.a=g("e");l.Ha=function(a){if(this.Y&&this.Y!=a)throw Error("Method not supported");Q.f.Ha.call(this,a)};l.fa=g("k");l.p=function(){this.e=this.k.createElement("div")};l.M=function(a){this.e=a};l.z=function(){this.i=true;this.o&&na(this.o,function(a){!a.i&&a.a()&&a.z()},void 0)};
l.ea=function(){this.o&&na(this.o,function(a){a.i&&a.ea()},void 0);this.pa&&Pb(this.pa);this.i=false};l.b=function(){Q.f.b.call(this);this.i&&this.ea();if(this.pa){this.pa.N();delete this.pa}this.o&&na(this.o,function(a){a.N()},void 0);!this.bb&&this.e&&jb(this.e);this.Y=this.mb=this.e=this.na=this.o=null};
l.removeChild=function(a,b){if(a){var c=p(a)?a:a.W||(a.W=":"+(a.jb.nb++).toString(36)),d;if(this.na&&c){d=this.na;d=c in d?d[c]:void 0;d=d||null}else d=null;a=d;if(c&&a){xa(this.na,c);pa(this.o,a);if(b){a.ea();a.e&&jb(a.e)}c=a;if(c==null)throw Error("Unable to set parent component");c.Y=null;Q.f.Ha.call(c,null)}}if(!a)throw Error("Child is not in parent component");return a};function R(a,b,c,d,e){Q.call(this,e);this.width=a;this.height=b;this.m=c||null;this.T=d||null}s(R,Q);R.prototype.j=null;R.prototype.G=0;R.prototype.L=0;R.prototype.q=function(){if(this.i)return D(this.a());if(q(this.width)&&q(this.height))return new u(this.width,this.height);return null};function Sb(a){var b=a.q();return b?b.width/(a.m?new u(a.m,a.T):a.q()).width:0};function Tb(a,b,c,d,e,f){if(arguments.length==6)this.setTransform(a,b,c,d,e,f);else if(arguments.length!=0)throw Error("Insufficient matrix parameters");else{this.A=this.C=1;this.u=this.B=this.I=this.J=0}}l=Tb.prototype;l.K=function(){return new Tb(this.A,this.u,this.B,this.C,this.I,this.J)};l.setTransform=function(a,b,c,d,e,f){if(!q(a)||!q(b)||!q(c)||!q(d)||!q(e)||!q(f))throw Error("Invalid transform parameters");this.A=a;this.u=b;this.B=c;this.C=d;this.I=e;this.J=f;return this};
l.scale=function(a,b){this.A*=a;this.u*=a;this.B*=b;this.C*=b;return this};l.translate=function(a,b){this.I+=a*this.A+b*this.B;this.J+=a*this.u+b*this.C;return this};l.rotate=function(a,b,c){var d=new Tb,e=Math.cos(a);a=Math.sin(a);b=d.setTransform(e,a,-a,e,b-b*e+c*a,c-b*a-c*e);c=this.A;d=this.B;this.A=b.A*c+b.u*d;this.B=b.B*c+b.C*d;this.I+=b.I*c+b.J*d;c=this.u;d=this.C;this.u=b.A*c+b.u*d;this.C=b.B*c+b.C*d;this.J+=b.I*c+b.J*d;return this};
l.toString=function(){return"matrix("+[this.A,this.u,this.B,this.C,this.I,this.J].join(",")+")"};function S(a,b){this.e=a;this.n=b;this.za=false}s(S,P);l=S.prototype;l.n=null;l.e=null;l.$a=null;l.a=g("e");l.addEventListener=function(a,b,c,d){Eb(this.e,a,b,c,d)};l.removeEventListener=function(a,b,c,d){Gb(this.e,a,b,c,d)};l.b=function(){S.f.b.call(this);Jb(this.e)};function T(a,b,c,d){S.call(this,a,b);this.Ja=c;this.n.Ga(this,c);this.Ca=d;this.n.Fa(this,d)}s(T,S);T.prototype.Ca=null;T.prototype.Ja=null;T.prototype.gb=g("Ca");T.prototype.hb=g("Ja");function Ub(a,b){S.call(this,a,b)}s(Ub,S);function Vb(a,b){S.call(this,a,b)}s(Vb,S);function Wb(a,b,c,d){T.call(this,a,b,c,d)}s(Wb,T);function Xb(a){S.call(this,null,a);this.o=[]}s(Xb,Ub);Xb.prototype.appendChild=function(a){this.o.push(a)};Xb.prototype.O=function(){for(var a=0,b=this.o.length;a<b;a++)Yb(this.n,this.o[a])};function Zb(a,b,c,d,e){T.call(this,a,b,d,e);this.Ia(c)}s(Zb,Wb);Zb.prototype.oa=false;Zb.prototype.Ia=function(a){this.ob=a.ia?a:lb(a);this.oa&&$b(this.n)};
Zb.prototype.O=function(a){this.oa=true;a.beginPath();kb(this.ob,function(b,c){switch(b){case 0:a.moveTo(c[0],c[1]);break;case 1:for(var d=0;d<c.length;d+=2)a.lineTo(c[d],c[d+1]);break;case 2:for(d=0;d<c.length;d+=6)a.bezierCurveTo(c[d],c[d+1],c[d+2],c[d+3],c[d+4],c[d+5]);break;case 3:throw Error("Canvas paths cannot contain arcs");case 4:a.closePath();break}})};function ac(a,b,c,d,e,f,h){S.call(this,a,b);this.vb=c;this.wb=d;this.ab=e;this.Ua=f;this.tb=h}s(ac,Vb);ac.prototype.oa=false;
ac.prototype.O=function(a){if(this.Va){this.ab&&this.Ua&&a.drawImage(this.Va,this.vb,this.wb,this.ab,this.Ua);this.oa=true}else{a=new Image;a.onload=ka(this.ib,this,a);a.src=this.tb}};ac.prototype.ib=function(a){this.Va=a;$b(this.n)};function bc(){};function cc(a,b){this.t=a;this.ga=b||1}s(cc,bc);function dc(a,b){this.La=a;this.t=b};function U(a,b,c,d,e){R.call(this,a,b,c,d,e)}s(U,R);U.prototype.Fa=function(){$b(this)};U.prototype.Ga=function(){$b(this)};function ec(a,b){var c=a.getContext();c.save();var d=b.$a?b.$a.K():new Tb,e=d.I,f=d.J;if(e||f)c.translate(e,f);(d=d.u)&&c.rotate(Math.asin(d))}U.prototype.p=function(){var a=this.k.p("div",{style:"position:relative;overflow:hidden"});this.e=a;this.ba=this.k.p("canvas");a.appendChild(this.ba);this.lb=this.j=new Xb(this);this.qb=0;fc(this)};
U.prototype.getContext=function(){this.a()||this.p();if(!this.S){this.S=this.ba.getContext("2d");this.S.save()}return this.S};U.prototype.q=function(){var a=this.width,b=this.height,c=p(a)&&a.indexOf("%")!=-1,d=p(b)&&b.indexOf("%")!=-1;if(!this.i&&(c||d))return null;var e,f;if(c){e=this.a().parentNode;f=D(e);a=parseFloat(a)*f.width/100}if(d){e=e||this.a().parentNode;f=f||D(e);b=parseFloat(b)*f.height/100}return new u(a,b)};
function fc(a){mb(a.a(),a.width,a.height);var b=a.q();if(b){mb(a.ba,b.width,b.height);a.ba.width=b.width;a.ba.height=b.height;a.S=null}}U.prototype.reset=function(){var a=this.getContext();a.restore();var b=this.q();b.width&&b.height&&a.clearRect(0,0,b.width,b.height);a.save()};function $b(a){if(a.Eb)a.Db=true;else if(a.i){a.reset();if(a.m){var b=a.q();a.getContext().scale(b.width/a.m,b.height/a.T)}if(a.G||a.L)a.getContext().translate(-a.G,-a.L);ec(a,a.j);a.j.O(a.S);a.getContext().restore()}}
function Yb(a,b){var c=a.getContext();ec(a,b);if(!b.gb||!b.hb)b.O(c);else{var d=b.Ca;if(d)if(d instanceof cc){if(d.ga!=0){c.globalAlpha=d.ga;c.fillStyle=d.t;b.O(c);c.fill();c.globalAlpha=1}}else{var e=c.createLinearGradient(d.zb(),d.Bb(),d.Ab(),d.Cb());e.addColorStop(0,d.xb());e.addColorStop(1,d.yb());c.fillStyle=e;b.O(c);c.fill()}if(d=b.Ja){b.O(c);c.strokeStyle=d.t;d=d.La;if(p(d)&&d.indexOf("px")!=-1)d=parseFloat(d)/Sb(a);c.lineWidth=d;c.stroke()}}a.getContext().restore()}l=U.prototype;
l.D=function(a,b){b=b||this.j;b.appendChild(a);this.i&&!this.qb&&!(b!=this.j&&b!=this.lb)&&Yb(this,a)};l.drawImage=function(a,b,c,d,e,f){a=new ac(null,this,a,b,c,d,e);this.D(a,f);return a};l.Aa=function(a,b,c,d){a=new Zb(null,this,a,b,c);this.D(a,d);return a};l.b=function(){this.S=null;U.f.b.call(this)};l.z=function(){var a=this.q();U.f.z.call(this);if(!a){fc(this);this.dispatchEvent("resize")}$b(this)};function gc(a,b){this.sa=a||1;this.ja=b||hc;this.ya=ka(this.ub,this);this.Ea=la()}s(gc,P);gc.prototype.enabled=false;var hc=o.window;l=gc.prototype;l.R=null;l.ub=function(){if(this.enabled){var a=la()-this.Ea;if(a>0&&a<this.sa*0.8)this.R=this.ja.setTimeout(this.ya,this.sa-a);else{this.dispatchEvent(ic);if(this.enabled){this.R=this.ja.setTimeout(this.ya,this.sa);this.Ea=la()}}}};l.start=function(){this.enabled=true;if(!this.R){this.R=this.ja.setTimeout(this.ya,this.sa);this.Ea=la()}};
l.stop=function(){this.enabled=false;if(this.R){this.ja.clearTimeout(this.R);this.R=null}};l.b=function(){gc.f.b.call(this);this.stop();delete this.ja};var ic="tick";function jc(a,b){S.call(this,a,b)}s(jc,Ub);function kc(a,b,c,d){T.call(this,a,b,c,d)}s(kc,Wb);kc.prototype.Ia=function(a){var b=this.a();a={d:lc(a)};for(var c in a)b.setAttribute(c,a[c])};function mc(a,b){S.call(this,a,b)}s(mc,Vb);function V(a,b,c,d,e){R.call(this,a,b,c,d,e);this.eb={};this.Ka=w&&!x(526);this.Q=new O(this)}var nc;s(V,R);function oc(a,b,c){a=a.k.w.createElementNS("http://www.w3.org/2000/svg",b);if(c)for(var d in c)a.setAttribute(d,c[d]);return a}l=V.prototype;l.D=function(a,b){(b||this.j).a().appendChild(a.a())};l.Fa=function(a,b){var c=a.a();if(b instanceof cc){c.setAttribute("fill",b.t);c.setAttribute("fill-opacity",b.ga)}else c.setAttribute("fill","none")};
l.Ga=function(a,b){var c=a.a();if(b){c.setAttribute("stroke",b.t);var d=b.La;p(d)&&d.indexOf("px")!=-1?c.setAttribute("stroke-width",parseFloat(d)/Sb(this)):c.setAttribute("stroke-width",d)}else c.setAttribute("stroke","none")};
l.p=function(){var a=oc(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=oc(this,"g");this.Pa=oc(this,"defs");this.j=new jc(b,this);a.appendChild(this.Pa);a.appendChild(b);this.e=a;if(this.m||this.G||this.L){this.a().setAttribute("preserveAspectRatio","none");this.Ka?this.xa():this.a().setAttribute("viewBox",this.G+" "+this.L+" "+(this.m?this.m+" "+this.T:""))}};
l.xa=function(){if(this.i&&(this.m||this.G||!this.L)){var a=this.q();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var b=-this.G,c=-this.L,d=a.width/this.m;a=a.height/this.T;this.j.a().setAttribute("transform","scale("+d+" "+a+") translate("+b+" "+c+")")}}};
l.q=function(){if(!Sa)return D(this.a());var a=this.width,b=this.height,c=p(a)&&a.indexOf("%")!=-1,d=p(b)&&b.indexOf("%")!=-1;if(!this.i&&(c||d))return null;var e,f;if(c){e=this.a().parentNode;f=D(e);a=parseFloat(a)*f.width/100}if(d){e=e||this.a().parentNode;f=f||D(e);b=parseFloat(b)*f.height/100}return new u(a,b)};
l.drawImage=function(a,b,c,d,e,f){a=oc(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new mc(a,this);this.D(e,f);return e};l.Aa=function(a,b,c,d){a=oc(this,"path",{d:lc(a)});b=new kc(a,this,b,c);this.D(b,d);return b};
function lc(a){var b=[];kb(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,Math.abs(e)>180?1:0,e>0?1:0,d[4],d[5]);break;case 4:b.push("Z");break}});return b.join(" ")}
V.prototype.z=function(){var a=this.q();V.f.z.call(this);a||this.dispatchEvent("resize");if(this.Ka){a=this.width;var b=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof b=="string"&&b.indexOf("%")!=-1&&Nb(this.Q,pc(),ic,this.xa);this.xa()}};V.prototype.ea=function(){V.f.ea.call(this);this.Ka&&Ob(this.Q,pc(),ic,this.xa)};V.prototype.b=function(){delete this.eb;delete this.Pa;delete this.j;V.f.b.call(this)};function pc(){if(!nc){nc=new gc(400);nc.start()}return nc};function qc(){return this.e=this.n.k.a(this.W)||this.e}function rc(a,b){this.W=a.id;S.call(this,a,b)}s(rc,Ub);rc.prototype.a=qc;function sc(a,b,c,d){this.W=a.id;T.call(this,a,b,c,d)}s(sc,Wb);sc.prototype.a=qc;sc.prototype.Ia=function(a){tc(this.a(),"path",uc(a))};function vc(a,b){this.W=a.id;S.call(this,a,b)}s(vc,Vb);vc.prototype.a=qc;function W(a,b,c,d,e){R.call(this,a,b,c,d,e);this.Q=new O(this)}s(W,R);var wc=document.documentMode&&document.documentMode>=8;function xc(a){var b;if(b=p(a)){b=a.length-1;b=b>=0&&a.indexOf("%",b)==b}return b?a:parseFloat(a.toString())+"px"}function X(a){return Math.round(parseFloat(a.toString())*100)}function tc(a,b,c){if(wc)a[b]=c;else a.setAttribute(b,c)}function yc(a,b){var c=a.k.createElement("g_vml_:"+b);c.id="goog_"+Ia++;return c}function zc(a){if(wc&&a.i)a.a().innerHTML=a.a().innerHTML}
W.prototype.D=function(a,b){(b||this.j).a().appendChild(a.a());zc(this)};W.prototype.Fa=function(a,b){var c=a.a();c.fillcolor="";for(var d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];e.tagName=="fill"&&c.removeChild(e)}if(b instanceof cc)if(b.t=="transparent")c.filled=false;else if(b.ga!=1){c.filled=true;d=yc(this,"fill");d.opacity=Math.round(b.ga*100)+"%";d.color=b.t;c.appendChild(d)}else{c.filled=true;c.fillcolor=b.t}else c.filled=false;zc(this)};
W.prototype.Ga=function(a,b){var c=a.a();if(b){c.stroked=true;var d=b.La;if(p(d)&&d.indexOf("px")==-1)d=parseFloat(d);else d*=Sb(this);var e=c.getElementsByTagName("stroke")[0];if(d<1){e=e||yc(this,"stroke");e.opacity=d;e.Fb="1px";e.color=b.t;c.appendChild(e)}else{e&&c.removeChild(e);c.strokecolor=b.t;c.strokeweight=d+"px"}}else c.stroked=false;zc(this)};
function Ac(a,b,c,d,e){var f=a.style;f.position="absolute";f.left=Math.round((parseFloat(b.toString())-0.5)*100)+"px";f.top=Math.round((parseFloat(c.toString())-0.5)*100)+"px";f.width=X(d)+"px";f.height=X(e)+"px";if(a.tagName=="shape")a.coordsize=X(d)+" "+X(e)}try{eval("document.namespaces")}catch(Bc){}l=W.prototype;
l.p=function(){var a=this.k.w;if(!a.namespaces.g_vml_){wc?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}"}a=this.width;var b=this.height,c=this.k.p("div",{style:"overflow:hidden;position:relative;width:"+xc(a)+";height:"+xc(b)});this.e=c;var d=yc(this,"group"),e=d.style;e.position="absolute";e.left=e.top=0;e.width=this.width;e.height=this.height;
d.coordsize=this.m?X(this.m)+" "+X(this.T):X(a)+" "+X(b);d.coordorigin=this.G!==undefined?X(this.G)+" "+X(this.L):"0 0";c.appendChild(d);this.j=new rc(d,this);Eb(c,"resize",ka(this.Da,this))};l.Da=function(){var a=D(this.a()),b=this.j.a().style;if(a.width){b.width=a.width+"px";b.height=a.height+"px"}else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&Nb(this.Q,a,"propertychange",this.Da)}this.dispatchEvent("resize")};
l.q=function(){var a=this.a();return new u(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};l.drawImage=function(a,b,c,d,e,f){var h=yc(this,"image");Ac(h,a,b,c,d);tc(h,"src",e);a=new vc(h,this);this.D(a,f);return a};l.Aa=function(a,b,c,d){var e=yc(this,"shape"),f=this.m?new u(this.m,this.T):this.q();Ac(e,0,0,f.width,f.height);tc(e,"path",uc(a));a=new sc(e,this,b,c);this.D(a,d);return a};
function uc(a){var b=[];kb(a,function(c,d){switch(c){case 0:b.push("m");Array.prototype.push.apply(b,oa(d,X));break;case 1:b.push("l");Array.prototype.push.apply(b,oa(d,X));break;case 2:b.push("c");Array.prototype.push.apply(b,oa(d,X));break;case 4:b.push("x");break;case 3:var e=d[2]+d[3];b.push("ae",X(d[4]-d[0]*Math.cos(y(e))),X(d[5]-d[1]*Math.sin(y(e))),X(d[0]),X(d[1]),Math.round(d[2]*-65536),Math.round(d[3]*-65536));break}});return b.join(" ")}
W.prototype.z=function(){W.f.z.call(this);this.Da();zc(this)};W.prototype.b=function(){this.j=null;W.f.b.call(this)};function Y(a,b,c,d,e,f){Q.call(this,f);this.$=a;this.ma=b;this.Ma=c;this.la=d||null;this.V=e||0}s(Y,Q);Y.prototype.M=function(a){Y.f.M.call(this,a);ua(this.a(),"goog-roundedpanel");this.l=this.fa().createElement("div");this.l.className="goog-roundedpanel-background";this.a().appendChild(this.l);a=this.a();this.da=eb(document,null,"goog-roundedpanel-content",a)[0];if(!this.da){this.da=this.fa().p("div");this.da.className="goog-roundedpanel-content";this.a().appendChild(this.da)}};
Y.prototype.b=function(){Y.f.b.call(this);if(this.l){this.fa().removeNode(this.l);this.l=null}this.da=null};function Cc(a,b,c,d,e,f){Y.call(this,a,b,c,d,e,f)}s(Cc,Y);
Cc.prototype.M=function(a){Cc.f.M.call(this,a);this.l.style.border=this.ma+"px solid "+this.Ma;if(this.la)this.l.style.backgroundColor=this.la;if(this.V==15)this.l.style[Dc(this,15)]=this.$+"px";else{var b=this.V&4?this.$:0;a=Dc(this,4);this.l.style[a]=b+"px";b=this.V&8?this.$:0;a=Dc(this,8);this.l.style[a]=b+"px";b=this.V&1?this.$:0;a=Dc(this,1);this.l.style[a]=b+"px";b=this.V&2?this.$:0;a=Dc(this,2);this.l.style[a]=b+"px"}};
function Dc(a,b){var c,d,e;if(w){d="Left";e="Right"}else{d="left";e="right"}switch(b){case 15:c="";break;case 4:c="Top"+d;break;case 8:c="Top"+e;break;case 2:c="Bottom"+d;break;case 1:c="Bottom"+e;break}return w?"WebkitBorder"+c+"Radius":"MozBorderRadius"+c}function Z(a,b,c,d,e,f){Y.call(this,a,b,c,d,e,f)}s(Z,Y);
Z.prototype.M=function(a){Z.f.M.call(this,a);a=D(this.a());this.ha=[];this.U=[];this.ka=[];this.wa=[];this.Ba=[];for(var b=this.ma*0.5,c,d,e,f,h,j,i=0;i<4;i++){h=Math.pow(2,i);c=h&this.V?this.$:0;switch(h){case 2:d=b+c;e=a.height-b;break;case 4:d=b;e=c+b;break;case 8:d=a.width-c-b;e=b;break;case 1:d=a.width-b;e=a.height-c-b;break}f=h&6?c+b:a.width-c-b;h=h&12?c+b:a.height-c-b;j=90*i;this.ha[i]=c;this.U[i]=new va(d,e);this.ka[i]=new va(f,h);this.wa[i]=j;this.Ba[i]=j+90}d=a.width;e=a.height;b=a.width;
a=a.height;c=this.fa();a=Ra?new W(d,e,b,a,c):w&&(!x("420")||Ta)?new U(d,e,b,a,c):new V(d,e,b,a,c);a.p();this.n=a;this.n.p();a=new A;for(d=0;d<4;d++)if(this.ha[d])a.arc(this.ka[d].x,this.ka[d].y,this.ha[d],this.ha[d],this.wa[d],this.Ba[d]-this.wa[d],d>0);else d==0?a.moveTo(this.U[d].x,this.U[d].y):a.lineTo(this.U[d].x,this.U[d].y);a.close();this.n.Aa(a,this.ma?new dc(this.ma,this.Ma):null,this.la?new cc(this.la,1):null);a=this.n;d=this.l;if(a.i)throw Error("Component already rendered");a.e||a.p();
d?d.insertBefore(a.e,null):a.k.w.body.appendChild(a.e);if(!a.Y||a.Y.i)a.z()};Z.prototype.b=function(){Z.f.b.call(this);this.n.N();delete this.n;delete this.ha;delete this.U;delete this.ka;delete this.wa;delete this.Ba};dom_=new cb;cornerdivs=dom_.cb("div","corners");
for(var Ec=0;Ec<cornerdivs.length;Ec++){corner=cornerdivs[Ec];if(corner.currentStyle)var Fc=corner.currentStyle.backgroundColor;else if(window.getComputedStyle)Fc=document.defaultView.getComputedStyle(corner,null).getPropertyValue("background-color");dom_.sb(corner,{style:"background-color: white"});var $=w&&x("500")||Sa&&x("1.9a")?new Cc(10,0,"#000000",Fc,15,void 0):new Z(10,0,"#000000",Fc,15,void 0),Gc=corner;if($.i)throw Error("Component already rendered");else if(Gc){$.bb=true;if(!$.k||$.k.w!=
db(Gc))$.k=bb(Gc);$.M(Gc);$.z()}else throw Error("Invalid element to decorate");};
